# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdcsisCpp <- function(stats_method, x, variable_index, y, z, bandwidth, distance_index, num_threads, num_bootstrap, seed, stats_type) {
    .Call(`_cdcsis_cdcsisCpp`, stats_method, x, variable_index, y, z, bandwidth, distance_index, num_threads, num_bootstrap, seed, stats_type)
}

